/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CursosTreinamentosRouteImport } from './routes/cursos.treinamentos'
import { Route as ApiPublicNewsletterRouteImport } from './routes/api/public/newsletter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosTreinamentosRoute = CursosTreinamentosRouteImport.update({
  id: '/cursos/treinamentos',
  path: '/cursos/treinamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNewsletterRoute = ApiPublicNewsletterRouteImport.update({
  id: '/api/public/newsletter',
  path: '/api/public/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cursos/treinamentos': typeof CursosTreinamentosRoute
  '/api/public/newsletter': typeof ApiPublicNewsletterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cursos/treinamentos': typeof CursosTreinamentosRoute
  '/api/public/newsletter': typeof ApiPublicNewsletterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cursos/treinamentos': typeof CursosTreinamentosRoute
  '/api/public/newsletter': typeof ApiPublicNewsletterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cursos/treinamentos' | '/api/public/newsletter'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cursos/treinamentos' | '/api/public/newsletter'
  id: '__root__' | '/' | '/cursos/treinamentos' | '/api/public/newsletter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CursosTreinamentosRoute: typeof CursosTreinamentosRoute
  ApiPublicNewsletterRoute: typeof ApiPublicNewsletterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/treinamentos': {
      id: '/cursos/treinamentos'
      path: '/cursos/treinamentos'
      fullPath: '/cursos/treinamentos'
      preLoaderRoute: typeof CursosTreinamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/newsletter': {
      id: '/api/public/newsletter'
      path: '/api/public/newsletter'
      fullPath: '/api/public/newsletter'
      preLoaderRoute: typeof ApiPublicNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CursosTreinamentosRoute: CursosTreinamentosRoute,
  ApiPublicNewsletterRoute: ApiPublicNewsletterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
